# Generated by Django 4.0.4 on 2022-05-26 05:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_juego_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_juegos'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='texto',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
