# Generated by Django 4.0.4 on 2022-05-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_juego_imagen_alter_juego_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotosjuegos'),
        ),
    ]
