# Generated by Django 4.0.4 on 2022-05-26 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_juego_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='autor',
        ),
    ]
