# Generated by Django 4.0.4 on 2022-05-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_remove_juego_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='autor',
            field=models.CharField(default='NN', max_length=50),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.CharField(blank=True, default='NN', max_length=50, null=True),
        ),
    ]
