# Generated by Django 4.0.4 on 2022-05-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_juego_autor_alter_noticia_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='autor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
