# Generated by Django 4.0.4 on 2022-05-26 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0013_alter_juego_autor_alter_noticia_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='autor',
        ),
        migrations.AddField(
            model_name='juego',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
