# Generated by Django 4.0.4 on 2022-05-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_remove_juego_autor_juego_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='author',
            new_name='autor',
        ),
    ]
