# Generated by Django 4.0.4 on 2022-05-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_alter_messagemodel_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='body',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
