# Generated by Django 4.0.4 on 2022-05-28 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_juego_autor_alter_juego_imagen_and_more'),
        ('App', '0021_messagemodel'),
    ]

    operations = [
    ]
