# Generated by Django 4.0.4 on 2022-05-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_merge_20220528_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadmodel',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='threadmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='MessageModel',
        ),
        migrations.DeleteModel(
            name='ThreadModel',
        ),
    ]
