# Generated by Django 4.0.4 on 2022-05-29 15:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_alter_noticia_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='texto',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
