# Generated by Django 4.0.4 on 2022-05-29 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_alter_noticia_autor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Integrante',
        ),
    ]
